from Locators.baseclass import Locators


class Data(Locators):
    system_users = 'https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers'
    emp_name = "m"
    user_input = "Dhanraj123"
    input_pw = "Manju@2522"
    input_confirm_pw = "Manju@2522"
    added_user_step_name = "user added"
    added_user_screenshot_name = "Successfully added user"
    deleted_user = "Deleted User"
    successfully_deleted_user = "successfully_deleted_user"
    expected_add_user_success_msg = "Successfully Saved"
    expected_delete_user_success_msg = "Successfully Deleted"
    Date = "12"
    Month = "October"
    Year = "2024"
    date = "14"
    month = "October"
    year = "2024"
    expected_leave_successful_msg = "Successfully Saved"
    input_keywords = ["python", ",allure", ",selenium"]
    recruitment_year = "2024"
    recruitment_month = "August"
    recruitment_date = "28"
    first_name = "Jos"
    last_name = "Butler"
    email = "jos_butler@gmail.com"
    contact_num = "9379309372"
    file_path = "C:/Users/manju/OneDrive/Documents/Allure installation and integration.txt"
    expected_recruitment_successful_msg = "Successfully Saved"
    candidate = first_name+" "+last_name
    added_recruitment_step_name = "Added Recruitment"
    added_recruitment_screenshot_name = "Successfully added recruitment to list"
    personal_first_name = "Jos"
    personal_last_name = "Butler"
    emp_id = personal_first_name + "123"
    driver_license_id = personal_first_name[:2] + personal_last_name[:2] + "280"
    licenseExpiryDate = "2026-10-12"
    info_year = "2001"
    info_month = "May"
    info_date = "2"
    expected_my_info_success_msg = "Successfully Saved"
